# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a2d0fd9a0fc542132ef2da25b7ba736b84f0e751fe8a29a568fbde7d7b67d497d59579c38acd5fc86db9a01397e7b05fcb9eb050a08d25503617e98644e91b

test:
  secret_key_base: c97871f8d3ee6c521eeec6e1ad5b615a8ccd950116ede0ef5acbe29d48f7f8f8b6ff89d6dbf33098eae6caedb46998f31661088b46b332eeb790a9d0d23d7292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
